SELECT * FROM goodee_ex.T_WORKTIME;
 -- INNER JOIN으로 푸는 법?
/**
SELECT 
  SEQ_VC, TIME_NU AS "시간",
  (SELECT COUNT(*) + 1 FROM T_WORKTIME WHERE TIME_NU < num2.TIME_NU) AS "순위" 
FROM T_WORKTIME AS num2
ORDER BY TIME_NU ASC;
*/
