SELECT * FROM employee.employees;

SELECT 
    CONCAT(FIRST_NAME," " ,LAST_NAME) AS "Name", SALARY
FROM
    employees
WHERE
DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME LIKE 'IT%')
   AND SALARY > (SELECT AVG(SALARY) FROM employees);
